event_inherited();
state = "chase";
hp = 80;
max_hp = hp;
chase_speed = random_range(0.35, 0.4);
max_chsae_speed = 2;
experience = random_range(60, 100);
attack_range = 115;
is_dead = 0;
backup_range = 96;